Fix/obj setting
compas-dev/compas_viewer pull request #181
Opened 2024-06-20 09:48 UTC by PingHsunTsai

### What type of change is this?

- [ ] Fixed `objectsetting` doesn't respone to `scenetree`
- [ ] Added `DefaultLayout` to handle gerneral `layout` setting to minimal.
- [ ] Added `TextEdit` to handle `name` change.
- [ ] Added `Observer` to handle `is_selected` state update or more.

2024-06-20 09:53 UTC, PingHsunTsai commented
The modified obj attributes are able to save to scene, but there is a problem to load the color attribute from scene, we can fo it in another PR

2024-06-26 08:38 UTC, Licini commented
This PR is now mixed with fixing the layout of object settings, and implementation of `Observer` which we might need more iterations vs `Signal` pattern. Can you isolate out the `Observer` part?

2024-06-26 08:58 UTC, PingHsunTsai commented
Yes, but the ability to open ObjectSetting from Sceneform selection will not be available for now(just a heads up).
I will try is there another quick solution.

2024-06-26 10:09 UTC, Licini commented
How about add the object settings cmd as callback function in the config of `SceneForm`?
```python
{
    "type": "Sceneform",
    "columns": [
        {"title": "Name", "type": "label", "text": lambda obj: obj.name},
        {"title": "Show", "type": "checkbox", "checked": lambda obj: obj.show, "action": lambda obj, checked: setattr(obj, "show", checked)},
    ],
    "on_select": obj_settings_cmd # something like this
},

```

2024-06-26 10:11 UTC, PingHsunTsai commented
yes on it!

2024-06-26 10:14 UTC, Licini commented
> How about add the object settings cmd as callback function in the config of `SceneForm`?
> 
> ```python
> {
>     "type": "Sceneform",
>     "columns": [
>         {"title": "Name", "type": "label", "text": lambda obj: obj.name},
>         {"title": "Show", "type": "checkbox", "checked": lambda obj: obj.show, "action": lambda obj, checked: setattr(obj, "show", checked)},
>     ],
>     "on_select": obj_settings_cmd # something like this
> },
> ```

Just realized there was already a `callback` parameter in `SceneForm` which does exactly this, you can use that directly. Let's just use name `callback` instead of `on_select`

2024-06-26 14:59 UTC, Licini commented
Some observations here:
1. the object setting form should hide when nothing selected
<img width="347" alt="image" src="https://github.com/compas-dev/compas_viewer/assets/17893605/bfed10b6-6414-4872-8154-a75c09f72d8f">

2. Name should not be number 
<img width="323" alt="image" src="https://github.com/compas-dev/compas_viewer/assets/17893605/d2c85dc7-4005-49d9-86a7-403a4057f97d">

3. Color picker is too thin in vertical direction 
<img width="284" alt="image" src="https://github.com/compas-dev/compas_viewer/assets/17893605/6caf86c0-60bf-47ee-b39b-345f345beeac">

4. The object form should be in a scrollable, right now the form has a fixed size, the portion between scene form and object form should be adjustable

2024-06-26 15:16 UTC, PingHsunTsai commented
regarding your first point @Licini  
I think Tom prefer to have a placeholder there, but I just added  `self.hide_widget = True` option in `SideBarRight`, so this can be decided by user as well.
For the scrolling space, it needs to be restructure a bit, cus it takes different type than layout, so I will propose we do it in another PR
The rest I will try to adjust them now.

2024-07-10 10:52 UTC, PingHsunTsai commented
Hi @Licini and @tomvanmele this PR is ready!

2024-07-12 08:29 UTC, Licini commented on src/compas_viewer/components/objectsetting.py
> +        self.setFixedHeight(200)
We should not set a fix height, the form should be allowed to adjusted vertically like this:
(also can you make the items vertically align to the top?)
<img width="269" alt="image" src="https://github.com/user-attachments/assets/c4d5ca05-87b0-4144-a176-06fd1a3c290c">

2024-07-12 08:37 UTC, Licini commented
Noticed some issues with spinbox:
1. Plz make the spinbox wider and show the digits after
2. use 1 decimal place instead of two
3. Make the step 0.1 instead of 1, right now if I click down arrow it set to value 0 and start to throw render errors. (linewidth value can not <= 0) .
<img width="212" alt="image" src="https://github.com/user-attachments/assets/d9abfb76-3cb5-4fd1-b42a-2f2efb820253">

2024-07-12 08:38 UTC, Licini requested changes
Looking much better! but still plz make the changes mentioned above

2024-07-12 13:01 UTC, Licini commented
one more question, how do you disable the object settings?

2024-07-12 15:43 UTC, PingHsunTsai commented
@Licini https://github.com/compas-dev/compas_viewer/pull/181/commits/d9369e2bbe5da214fba75623c3bab9dd1dfbc483
I just add a setter here

2024-07-18 17:05 UTC, Licini commented
Thanks @PingHsunTsai ! Merging Finally!

2024-07-18 17:05 UTC, merged